openapi: "3.0.2"
info:
    title: AirBnB - API
    version: "1.0"
servers:
    - url: https://api.server.test/v1
tags:
    - name: Homestay
      description: Endpoints related to homestay management
    - name: Booking
      description: Endpoints related to booking management
paths:
    /homestays:
        post:
            security:
                - BearerAuth: []
            tags:
                - Homestay
            summary: Create new homestay
            description: Create new homestay
            requestBody:
                required: true
                content:
                    application/json:
                        schema:
                            $ref: "#/components/schemas/GetHomestay"
                        example:
                            host_id: 1
                            title: Homestay 1
                            description: Homestay 1 description
                            location: Bali
                            price: $25
                            facilities: wifi, kitchen
                            images: image link

            responses:
                "200":
                    description: Success create new homestay
                    content:
                        application/json:
                            schema:
                                type: object
                                properties:
                                    message:
                                        type: string
                                    data:
                                        $ref: "#/components/schemas/GetHomestay"
                            example:
                                message: Success create new homestay
                                data:
                                    host_id: 1
                                    title: Homestay 1
                                    description: Homestay 1 description
                                    location: Bali
                                    price: $25
                                    facilities: wifi, kitchen
                                    images: image link
                "500":
                    description: Internal server error
                    content:
                        application/json:
                            schema:
                                $ref: "#/components/schemas/GetHomestay"
                            example:
                                message: Internal Server Error
                                data: null
        get:
            security:
                - BearerAuth: []
            tags:
                - Homestay
            summary: Retrieve all homestay
            description: Retrieve all homestay
            responses:
                "200":
                    description: Success retrieve all homestay
                    content:
                        application/json:
                            schema:
                                type: object
                                properties:
                                    message:
                                        type: string
                                    data:
                                        $ref: "#/components/schemas/GetHomestay"
                            example:
                                message: Success retrieve all homestay
                                data:
                                    host_id: 1
                                    title: Homestay 1
                                    description: Homestay 1 description
                                    location: Bali
                                    price: $25
                                    facilities: wifi, kitchen
                                    images: image link
                "404":
                    description: The requested resource was not found
                    content:
                        application/json:
                            schema:
                                $ref: "#/components/schemas/GetHomestay"
                            example:
                                message: Data not found
                                data: null
                "500":
                    description: Internal server error
                    content:
                        application/json:
                            schema:
                                $ref: "#/components/schemas/GetHomestay"
                            example:
                                message: Internal Server Error
                                data: null
    /homestays/{homestay_id}:
        get:
            security:
                - BearerAuth: []
            tags:
                - Homestay
            summary: Retrieve specific homestay
            description: Retrieve specific homestay
            parameters:
                - name: homestay_id
                  in: path
                  required: true
                  description: Get homestay by its id
                  schema:
                      type: integer
                  examples:
                      param 1:
                          description: Example homestay id for Homestay 1
                          value: 1
                      param 2:
                          description: Example homestay id for Homestay 2
                          value: 2
            responses:
                "200":
                    description: Success retrieve specific homestay
                    content:
                        application/json:
                            schema:
                                type: object
                                properties:
                                    message:
                                        type: string
                                    data:
                                        $ref: "#/components/schemas/GetHomestay"
                            example:
                                message: Success retrieve specific homestay
                                data:
                                    host_id: 1
                                    title: Homestay 1
                                    description: Homestay 1 description
                                    location: Bali
                                    price: $25
                                    facilities: wifi, kitchen
                                    images: image link
                "404":
                    description: The requested resource was not found
                    content:
                        application/json:
                            schema:
                                $ref: "#/components/schemas/GetHomestay"
                            example:
                                message: Data not found
                                data: null
                "500":
                    description: Internal server error
                    content:
                        application/json:
                            schema:
                                $ref: "#/components/schemas/GetHomestay"
                            example:
                                message: Internal Server Error
                                data: null
        put:
            security:
                - BearerAuth: []
            tags:
                - Homestay
            summary: Update specific homestay
            description: Update specific homestay
            parameters:
                - name: homestay_id
                  in: path
                  required: true
                  description: Update homestay by its id
                  schema:
                      type: integer
                  examples:
                      param 1:
                          description: Example homestay id for Homestay 1
                          value: 1
                      param 2:
                          description: Example homestay id for Homestay 2
                          value: 2
            requestBody:
                required: true
                content:
                    application/json:
                        schema:
                            $ref: "#/components/schemas/GetHomestay"
                        example:
                            host_id: 2
                            title: Homestay 2
                            description: Homestay 2 description
                            location: Jakarta
                            price: $30
                            facilities: wifi
                            images: image link
            responses:
                "200":
                    description: Success update specific homestay
                    content:
                        application/json:
                            schema:
                                type: object
                                properties:
                                    message:
                                        type: string
                                    data:
                                        $ref: "#/components/schemas/GetHomestay"
                            example:
                                message: Success retrieve specific homestay
                                data:
                                    host_id: 2
                                    title: Homestay 2
                                    description: Homestay 2 description
                                    location: Jakarta
                                    price: $30
                                    facilities: wifi
                                    images: image link
                "404":
                    description: The requested resource was not found
                    content:
                        application/json:
                            schema:
                                $ref: "#/components/schemas/GetHomestay"
                            example:
                                message: Data not found
                                data: null
                "500":
                    description: Internal server error
                    content:
                        application/json:
                            schema:
                                $ref: "#/components/schemas/GetHomestay"
                            example:
                                message: Internal Server Error
                                data: null
        delete:
            security:
                - BearerAuth: []
            tags:
                - Homestay
            summary: Delete specific homestay
            description: Delete specific homestay
            parameters:
                - name: homestay_id
                  in: path
                  required: true
                  description: Delete homestay by its id
                  schema:
                      type: integer
                  examples:
                      param 1:
                          description: Example homestay id for Homestay 1
                          value: 1
                      param 2:
                          description: Example homestay id for Homestay 2
                          value: 2
            responses:
                "200":
                    description: Success delete specific homestay
                    content:
                        application/json:
                            schema:
                                type: object
                                properties:
                                    message:
                                        type: string
                                    data:
                                        $ref: "#/components/schemas/GetHomestay"
                            example:
                                message: Success delete specific homestay
                                data:
                                    host_id: 2
                                    title: Homestay 2
                                    description: Homestay 2 description
                                    location: Jakarta
                                    price: $30
                                    facilities: wifi
                                    images: image link
                "404":
                    description: The requested resource was not found
                    content:
                        application/json:
                            schema:
                                $ref: "#/components/schemas/GetHomestay"
                            example:
                                message: Data not found
                                data: null
                "500":
                    description: Internal server error
                    content:
                        application/json:
                            schema:
                                $ref: "#/components/schemas/GetHomestay"
                            example:
                                message: Internal Server Error
                                data: null
    /bookings:
        post:
            security:
                - BearerAuth: []
            tags:
                - Booking
            summary: Create new booking
            description: Create new booking
            requestBody:
                required: true
                content:
                    application/json:
                        schema:
                            $ref: "#/components/schemas/GetBooking"
                        example:
                            customer_id: 1
                            homestay_id: 1
                            payment_id: 1
                            check_in_date: 2020-05-01
                            check_out_date: 2020-05-02
                            booking_status: booked
                            number_of_nights: 1
                            total_price: $30

            responses:
                "200":
                    description: Success create new homestay
                    content:
                        application/json:
                            schema:
                                type: object
                                properties:
                                    message:
                                        type: string
                                    data:
                                        $ref: "#/components/schemas/GetHomestay"
                            example:
                                message: Success create new booking
                                data:
                                    customer_id: 1
                                    homestay_id: 1
                                    homestay:
                                        host_id: 2
                                        title: Homestay 2
                                        description: Homestay 2 description
                                        location: Jakarta
                                        price: $30
                                        facilities: wifi
                                    payment_id: 1
                                    check_in_date: 2020-05-01
                                    check_out_date: 2020-05-02
                                    booking_status: booked
                                    number_of_nights: 1
                                    total_price: $30
                "500":
                    description: Internal server error
                    content:
                        application/json:
                            schema:
                                $ref: "#/components/schemas/GetHomestay"
                            example:
                                message: Internal Server Error
                                data: null
        delete:
            security:
                - BearerAuth: []
            tags:
                - Booking
            summary: Cancel booking
            description: Cancel booking
            parameters:
                - name: booking_id
                  in: path
                  required: true
                  description: Delete booking by its id
                  schema:
                      type: integer
                  examples:
                      param 1:
                          description: Example booking id for Homestay 1
                          value: 1
                      param 2:
                          description: Example booking id for Homestay 2
                          value: 2
            responses:
                "200":
                    description: Success cancelled booking
                    content:
                        application/json:
                            schema:
                                type: object
                                properties:
                                    message:
                                        type: string
                                    data:
                                        $ref: "#/components/schemas/GetHomestay"
                            example:
                                message: Success cancelled booking
                                data:
                                    customer_id: 1
                                    homestay_id: 1
                                    homestay:
                                        host_id: 2
                                        title: Homestay 2
                                        description: Homestay 2 description
                                        location: Jakarta
                                        price: $30
                                        facilities: wifi
                                    payment_id: 1
                                    check_in_date: 2020-05-01
                                    check_out_date: 2020-05-02
                                    booking_status: booked
                                    number_of_nights: 1
                                    total_price: $30
                "500":
                    description: Internal server error
                    content:
                        application/json:
                            schema:
                                $ref: "#/components/schemas/GetHomestay"
                            example:
                                message: Internal Server Error
                                data: null
components:
    securitySchemes:
        BearerAuth:
            description: "Authentication for AirBnB RESTful API"
            type: http
            scheme: bearer
    schemas:
        GetHomestay:
            type: object
            properties:
                host_id:
                    type: integer
                    format: int64
                title:
                    type: string
                description:
                    type: string
                location:
                    type: string
                price:
                    type: number
                    format: double
                facilities:
                    type: string
                images:
                    type: string
        GetBooking:
            type: object
            properties:
                customer_id:
                    type: integer
                    format: int64
                homestay_id:
                    type: integer
                    format: int64
                payment_id:
                    type: integer
                    format: int64
                check_in_date:
                    type: string
                check_out_date:
                    type: string
                booking_status:
                    type: string
                number_of_nights:
                    type: integer
                    format: int64
                total_price:
                    type: number
                    format: double
